# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/nn_creator/forms/ui/CreateProjectDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProjectDialog(object):
    def setupUi(self, CreateProjectDialog):
        CreateProjectDialog.setObjectName("CreateProjectDialog")
        CreateProjectDialog.resize(830, 176)
        CreateProjectDialog.setMinimumSize(QtCore.QSize(830, 176))
        CreateProjectDialog.setMaximumSize(QtCore.QSize(830, 176))
        self.horizontalLayoutWidget = QtWidgets.QWidget(CreateProjectDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(600, 120, 199, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.create_project_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.create_project_btn.setObjectName("create_project_btn")
        self.horizontalLayout_2.addWidget(self.create_project_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(CreateProjectDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 791, 101))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.project_name_LE = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.project_name_LE.setObjectName("project_name_LE")
        self.verticalLayout_2.addWidget(self.project_name_LE)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.project_path_LE = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.project_path_LE.setObjectName("project_path_LE")
        self.horizontalLayout_4.addWidget(self.project_path_LE)
        self.open_dir_btn = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.open_dir_btn.setObjectName("open_dir_btn")
        self.horizontalLayout_4.addWidget(self.open_dir_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.task_CB = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.task_CB.setObjectName("task_CB")
        self.verticalLayout_2.addWidget(self.task_CB)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 20)

        self.retranslateUi(CreateProjectDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateProjectDialog)

    def retranslateUi(self, CreateProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateProjectDialog.setWindowTitle(_translate("CreateProjectDialog", "NN-creater Create project"))
        self.cancel_btn.setText(_translate("CreateProjectDialog", "Cancel"))
        self.create_project_btn.setText(_translate("CreateProjectDialog", "Create"))
        self.label_3.setText(_translate("CreateProjectDialog", "Project Name"))
        self.label.setText(_translate("CreateProjectDialog", "Location"))
        self.label_2.setText(_translate("CreateProjectDialog", "Type"))
        self.open_dir_btn.setText(_translate("CreateProjectDialog", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateProjectDialog = QtWidgets.QDialog()
    ui = Ui_CreateProjectDialog()
    ui.setupUi(CreateProjectDialog)
    CreateProjectDialog.show()
    sys.exit(app.exec_())
