# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/nn_creator/forms/ui/StartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NNCreatorStartWindow(object):
    def setupUi(self, NNCreatorStartWindow):
        NNCreatorStartWindow.setObjectName("NNCreatorStartWindow")
        NNCreatorStartWindow.resize(927, 703)
        self.centralwidget = QtWidgets.QWidget(NNCreatorStartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 901, 621))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 881, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_project_LE = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.search_project_LE.setObjectName("search_project_LE")
        self.horizontalLayout.addWidget(self.search_project_LE)
        self.new_project_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.new_project_btn.setObjectName("new_project_btn")
        self.horizontalLayout.addWidget(self.new_project_btn)
        self.open_project_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_project_btn.setObjectName("open_project_btn")
        self.horizontalLayout.addWidget(self.open_project_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.projects_LV = QtWidgets.QListView(self.verticalLayoutWidget)
        self.projects_LV.setObjectName("projects_LV")
        self.verticalLayout.addWidget(self.projects_LV)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        NNCreatorStartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NNCreatorStartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 25))
        self.menubar.setObjectName("menubar")
        NNCreatorStartWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NNCreatorStartWindow)
        self.statusbar.setObjectName("statusbar")
        NNCreatorStartWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NNCreatorStartWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NNCreatorStartWindow)

    def retranslateUi(self, NNCreatorStartWindow):
        _translate = QtCore.QCoreApplication.translate
        NNCreatorStartWindow.setWindowTitle(_translate("NNCreatorStartWindow", "Neural network creator"))
        self.new_project_btn.setText(_translate("NNCreatorStartWindow", "New Project"))
        self.open_project_btn.setText(_translate("NNCreatorStartWindow", "Open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("NNCreatorStartWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("NNCreatorStartWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NNCreatorStartWindow = QtWidgets.QMainWindow()
    ui = Ui_NNCreatorStartWindow()
    ui.setupUi(NNCreatorStartWindow)
    NNCreatorStartWindow.show()
    sys.exit(app.exec_())
